import Head from 'next/head';

import { ScreenshotUpload } from '~/app/_components/file_upload';

export default function Home() {
  // const hello = api.post.hello.useQuery({ text: 'from tRPC' });

  return (
    <>
      <Head>
        <title>A Math Tutor</title>
        <meta name="description" content="Math Made Easy | Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-5 px-4 py-16">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Math <span className="text-[hsl(280,100%,70%)]">Tutor</span>
          </h1>
          <div className="text text-white">
            π/ Take a photo of your math problem and get step-by-step solutions instantly /π
          </div>
        </div>

        <div className="flex justify-content-center text-white">
          <ScreenshotUpload />
        </div>
      </main>
    </>
  );
}
